### ISSUE TITLE
delay between reply arriving to buddypress and email notification

### ISSUE THREAD

**Issue by mtadams4** [r-a-y/bp-reply-by-email#72] opened 2015-09-28 20:56 UTC
Hi r-a-y,

I am experiencing a delay of about 1.5 hours from when I reply by email and when receiving the email notification of the reply.

I have check the buddypress inbox and find that after replying by email, the message shows up successfully in buddypress within a minute or so.

Therefore, there is some holdup between when buddypress receives the message and sending out the email notification.

This is strange because when a message is sent from buddypress to another user on buddypress, the email notification comes right away. So it's just when using RBE that the email notification is delayed.

I have been continuously logged into the wordpress site. 
![screen shot 2015-09-28 at 4 54 23 pm](https://cloud.githubusercontent.com/assets/14783651/10148489/d440f4ac-6601-11e5-9ec3-2cb428f4f5aa.png)

**Comment by r-a-y** [comment] 2015-09-28 21:07
If the reply is showing up in your BuddyPress private message Inbox, this means that the issue is not related to RBE.  RBE uses native BuddyPress functions to post the private message reply.  Therefore, BuddyPress should send the email.

To be sure, please check your server's email log to verify the sent timestamps.

**Comment by mtadams4** [comment] 2015-09-29 18:16
Hi r-a-y, You can close the ticket. I checked the timestamps. The
timestamps looked fine and matched up with when the emails should have been
sent.
I tested with aol and gmail accounts and the responses from aol are now
working.

I did find one interesting thing though which could explain the more recent
issue with some of the gmail replies. When testing, I used a user email
address that forwarded to another email account. When replying back from
the address that had been forwarded to, the mail gets back to buddypress
but then there is the time lag. The problem went away when I added the
email address to my gmail account. When I replied back from the user's
email address it worked fine. -- Therefore, replying from a non-user
address to an RBE message is creating a issue with buddypress' notification
email.

On Mon, Sep 28, 2015 at 5:07 PM, r-a-y <notifications@github.com> wrote:

> If the reply is showing up in your BuddyPress private message Inbox, this
> means that the issue is not related to RBE. RBE uses native BuddyPress
> functions to post the private message reply. Therefore, BuddyPress should
> send the email.
>
> To be sure, please check your server's email log to verify the sent
> timestamps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/r-a-y/bp-reply-by-email/issues/72#issuecomment-143874554>
> .
>



-- 
Jonah G. Bernstein
(617) 383-7817
jonahbernstein@gmail.com

**Comment by r-a-y** [comment] 2015-09-29 19:09
>  When testing, I used a user email address that forwarded to another email account.

I can see how that would cause a problem.  RBE relies on the registered email address of the user, so if you are not replying via that email address, RBE will not post the message for security reasons.

Thanks for looking into the email logs.  Going to close this one.

**Closed by r-a-y** 2015-09-29 19:09 UTC
